In [1]:
import numpy as np
import math

def gauss(A, b):
    n = A.shape[0]
    
    for k in range(n):
        b[k] = b[k] / A[k][k]
        A[k] = A[k] / A[k][k]
        for i in range(k + 1, n):
            t = A[i][k]
            A[i] = A[i] - A[k] * t
            b[i] = b[i] - b[k] * t
    
    for k in reversed(range(n)):
        for i in range(k + 1, n):
            b[k] = b[k] - b[i] * A[k][i]
    
    return b


def norm(a):
    x = 0.0
    for i in a:
        x = x + (i * i)
    
    return math.sqrt(x)

def iterations(C, d, eps):
    x = d
    lx = 0
    while norm(lx - x) > eps:
        lx = x
        x = np.matmul(C, x) + d
    
    return x


def jacobi(A, b, eps):
    n = A.shape[0]
    
    for i in range(n):
        b[i] = b[i] / A[i][i]
        A[i] = -A[i] / A[i][i]
        A[i][i] = 0
    
    return iterations(A, b, eps)

X = np.array([7.01, 0.93, 0.75, 0.53, 0.22, 3.67, 0.31, 0.57, 0.46, 0.67, 9.16, 0.69, 0.82, 0.37, 0.35, 7.24]).reshape(4, 4)
y = np.array([-13, 6, 12, 2], dtype=float)

print(gauss(X, y))

X = np.array([7.01, 0.93, 0.75, 0.53, 0.22, 3.67, 0.31, 0.57, 0.46, 0.67, 9.16, 0.69, 0.82, 0.37, 0.35, 7.24]).reshape(4, 4)
y = np.array([-13, 6, 12, 2], dtype=float)

print(jacobi(X, y, 0.00000001))

X = np.array([7.01, 0.93, 0.75, 0.53, 0.22, 3.67, 0.31, 0.57, 0.46, 0.67, 9.16, 0.69, 0.82, 0.37, 0.35, 7.24]).reshape(4, 4)
y = np.array([-13, 6, 12, 2], dtype=float)

print(np.linalg.solve(X, y))


[-2.23257321  1.60103911  1.27600715  0.38559711]
[-2.23257321  1.60103911  1.27600715  0.38559711]
[-2.23257321  1.60103911  1.27600715  0.38559711]


In [2]:
print(X)

[[7.01 0.93 0.75 0.53]
 [0.22 3.67 0.31 0.57]
 [0.46 0.67 9.16 0.69]
 [0.82 0.37 0.35 7.24]]
